# Generated by Django 5.2.8 on 2025-11-13 12:53

import api.validators.accuracies_validator
import api.validators.classification_validator
import api.validators.positions_validator
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('accuracies', models.JSONField(validators=[api.validators.accuracies_validator.validate_accuracies])),
                ('classifications', models.JSONField(validators=[api.validators.classification_validator.validate_classifications])),
                ('positions', models.JSONField(validators=[api.validators.positions_validator.validate_positions])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
