/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesDetailRouteImport } from './routes/games/$detail'
import { Route as GamesAnalysisIndexRouteImport } from './routes/games/analysis/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDetailRoute = GamesDetailRouteImport.update({
  id: '/games/$detail',
  path: '/games/$detail',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesAnalysisIndexRoute = GamesAnalysisIndexRouteImport.update({
  id: '/games/analysis/',
  path: '/games/analysis/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/$detail': typeof GamesDetailRoute
  '/games': typeof GamesIndexRoute
  '/login': typeof LoginIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/register': typeof RegisterIndexRoute
  '/games/analysis': typeof GamesAnalysisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/$detail': typeof GamesDetailRoute
  '/games': typeof GamesIndexRoute
  '/login': typeof LoginIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/register': typeof RegisterIndexRoute
  '/games/analysis': typeof GamesAnalysisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/$detail': typeof GamesDetailRoute
  '/games/': typeof GamesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/games/analysis/': typeof GamesAnalysisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/$detail'
    | '/games'
    | '/login'
    | '/notifications'
    | '/register'
    | '/games/analysis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/$detail'
    | '/games'
    | '/login'
    | '/notifications'
    | '/register'
    | '/games/analysis'
  id:
    | '__root__'
    | '/'
    | '/games/$detail'
    | '/games/'
    | '/login/'
    | '/notifications/'
    | '/register/'
    | '/games/analysis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesDetailRoute: typeof GamesDetailRoute
  GamesIndexRoute: typeof GamesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  GamesAnalysisIndexRoute: typeof GamesAnalysisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$detail': {
      id: '/games/$detail'
      path: '/games/$detail'
      fullPath: '/games/$detail'
      preLoaderRoute: typeof GamesDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/analysis/': {
      id: '/games/analysis/'
      path: '/games/analysis'
      fullPath: '/games/analysis'
      preLoaderRoute: typeof GamesAnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesDetailRoute: GamesDetailRoute,
  GamesIndexRoute: GamesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  GamesAnalysisIndexRoute: GamesAnalysisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
